### PR TITLE
A warning message shows up on empty text entry. closes #60.

### LINKED ISSUE #60: Preventing from empty diary text
I'm not sure whether it's good to just have a warning message or a message that forces user to enter diary text, because sometimes user may only want to enter the title for some remembrance reason.

So let's first add a warning message that warns user to not let the diary text be empty.

### PR DESCRIPTION
**Pull request by mahditakrim**
Resolving https://github.com/emvigo/turbodiary/issues/60

When user enters a empty diary text a warning prompt message shows up, if user enters 'y' then empty diary text will save otherwise it goes back to getting diary text entry.

### CODE REVIEW

**Comment by emvigo** [comment]
I'll take a look at this later this day or maybe tomorrow. Thanks for the PR, in the meantime. From a *very* quick look at it, it looks promising.

**Comment by mahditakrim** [comment]
Dear @emvigo ,
Are you alive ?

**Comment by mahditakrim** [comment]
@RibalGZ ,
Do you know where @emvigo is ?

**Comment by emvigo** [comment]
Hi!
I'm sorry: I've been through some personal and family stuff lately, so I haven't been able to take a serious look at your PR. There are a couple of problems with your specific solution (the idea, as I told you is great, I'd like to see this implemented): have a look at the comments on your commit.
Happy New Year!

**Pull request closed without merging**
