### PR TITLE
Unusable includes cleaned and added some includes for portability reason. Closes #46

### LINKED ISSUE #46: Review #include directives
It's pretty normal that in any project #include's become cluttered, some are not even needed anymore, and some things may even be missing even if we're compiling with extra warnings. [`deheader'](http://www.catb.org/~esr/deheader/) shows some interesting results, although some seem to be false positives.

Using the "good first issue" for the first time, in case someone's looking for something easy to contribute with (idk how effective these tags are).

### PR DESCRIPTION
**Pull request by mahditakrim**
Resolving https://github.com/emvigo/turbodiary/issues/46
includes cleaned by removing unusable ones and added some includes for portability reason
and also fixed some include order.

### CODE REVIEW

**Comment by mahditakrim** [comment]
Dear @emvigo ,
Feel free to ask, comment and request, I'll be happy.

**Comment by mahditakrim** [comment]
Got it, and I'm going to fix it.

**Comment by mahditakrim** [comment]
Dear @emvigo ,
I did what you said and used commit --amend, push --force (learned that it forces the PR to change its commit).
So I have to send a new PR or it will work like this ?

**Comment by emvigo** [comment]
> Dear @emvigo ,
> I did what you said and used commit --amend, push --force (learned that it forces the PR to change its commit).
> So I have to send a new PR or it will work like this ?

Merged! :dancer: Thank you for your time!
No, PRs in Github are branch-based. "Destructive" operations like amending and rebasing don't need filing a new PR.

**Pull request merged**
